In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
def  initialize_parameters(layer_dims):

    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters

In [6]:
def linear_forward(A_Prev, W, b):

    Z = np.dot(W.T, A_Prev) + b

    return Z

In [7]:
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2

    for l in range (1, L+1):
        A_prev = A
        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]
        print("A" + str(l-1) + " : " , A_prev)
        print("W" + str(l) + " : " , W1)
        print("b" + str(l) + " : ", b1)
        print("--" * 20)

        A = linear_forward(A_prev, W1, b1)
        print("A" + str(l) + " : ", A)
        print("**" * 20)

    return A, A_prev

In [8]:
def update_parameters(parameters, y, y_hat, A1, X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)* parameters['W2'][0][0]* X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)* parameters['W2'][0][0]* X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)* parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)* parameters['W2'][1][0]* X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)* parameters['W2'][1][0]* X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)* parameters['W2'][1][0])

In [9]:
parameters = initialize_parameters([2,2,1])

for i in range (df.shape[0]):
        #
        X = df[['cgpa', 'profile_score']].values[i].reshape(2,1)
        y = df[['lpa']].values[i][0]

        print("\n\nForward propagation....")
        # parameter initialization
        y_hat, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]

        print("Backward propagation....")
        update_parameters(parameters, y, y_hat, A1, X)

        print("\nUpdated parameters....")
        print(parameters)



Forward propagation....
A0 :  [[8]
 [8]]
W1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1 :  [[1.6]
 [1.6]]
****************************************
A1 :  [[1.6]
 [1.6]]
W2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2 :  [[0.32]]
****************************************
Backward propagation....

Updated parameters....
{'W1': array([[0.10658137, 0.10658137],
       [0.10658137, 0.10658137]]), 'b1': array([[0.00082267],
       [0.00082267]]), 'W2': array([[0.111776],
       [0.111776]]), 'b2': array([[0.00736]])}


Forward propagation....
A0 :  [[7]
 [9]]
W1 :  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1 :  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1 :  [[1.70612461]
 [1.70612461]]
****************************************
A1 :  [[1.70612461]
 [1.70612461]]
W2 :  [[0.111776]
 [0.111776]]
b2 :  [[0.00736]]
----------------------------------------
A2 :  [[0.38876757]]
**********

In [10]:
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2

    for l in range (1, L+1):
        A_prev = A
        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]
#         print("A" + str(l-1) + " : " , A_prev)
#         print("W" + str(l) + " : " , W1)
#         print("b" + str(l) + " : ", b1)
#         print("--" * 20)

        A = linear_forward(A_prev, W1, b1)
#         print("A" + str(l) + " : ", A)
#         print("**" * 20)

    return A, A_prev

In [11]:
parameters = initialize_parameters([2,2,1])
epochs =5

for i in range(epochs):
    loss = []

    for j in range (df.shape[0]):
        #
        X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
        y = df[['lpa']].values[j][0]

        # parameter initialization
        y_hat, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A1, X)

        loss.append((y - y_hat)**2)

    print(f'Epoch - {i+1}, loss - {np.array(loss).mean()}\n\n\n')

Epoch - 1, loss - 26.28249792398698



Epoch - 2, loss - 19.438253848220803



Epoch - 3, loss - 10.139874435827522



Epoch - 4, loss - 3.385561305106485



Epoch - 5, loss - 1.3198454128484565





In [12]:
parameters

{'W1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}

In [13]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [14]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.get_weights()

[array([[-0.34988868, -0.16375852],
        [-0.00637674,  1.0976993 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.88645947],
        [-0.19900727]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
new_weights = [np.array([[0.1, 0.1], [0.1,  0.1 ]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[ 0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [20]:
model.set_weights(new_weights)

In [21]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [25]:
model.fit(df[['cgpa', 'profile_score']].values, df['lpa'].values, epochs=75,verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.8737
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5546
Epoch 3/75
4/4 [==============================] - 0s 4ms/step - loss: 27.2408
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.9038
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 26.5273
Epoch 6/75
4/4 [==============================] - 0s 5ms/step - loss: 26.1715
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 25.8216
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4419
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0280
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 24.6453
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 24.1983
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.7772
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [26]:
model.get_weights()

[array([[0.37365255, 0.37365255],
        [0.3659122 , 0.3659122 ]], dtype=float32),
 array([0.27249423, 0.27249423], dtype=float32),
 array([[0.3731108],
        [0.3731108]], dtype=float32),
 array([0.20505069], dtype=float32)]

In [27]:
parameters

{'W1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}