In [12]:
with open("/content/dataset.txt", "r") as file:
  # content = file.read()
  # print(content)

  lines = [line for line in file if line.strip()]

  content = "".join(lines)
  print(content)

I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the Army. Having completed my studies there, I was duly attached to the Fifth Northumberland Fusiliers as assistant surgeon. The regiment was stationed in India at the time, and before I could join it, the second Afghan war had broken out. On landing at Bombay, I learned that my corps had advanced through the passes, and was already deep in the enemy's country. I followed, however, with many other officers who were in the same situation as myself, and succeeded in reaching Candahar in safety, where I found my regiment, and at once entered upon my new duties.
The campaign brought honours and promotion to many, but for me it had nothing but misfortune and disaster. I was removed from my brigade and attached to the Berkshires, with whom I served at the fatal battle of Maiwand. There I was struck on the shoulder by a Jezail bullet, which shattered 

In [13]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [14]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([content])

In [33]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'and': 3,
 'to': 4,
 'a': 5,
 'i': 6,
 'he': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'was': 11,
 'his': 12,
 'you': 13,
 'had': 14,
 'is': 15,
 'which': 16,
 'with': 17,
 'as': 18,
 'have': 19,
 'my': 20,
 'at': 21,
 'for': 22,
 'there': 23,
 'be': 24,
 'this': 25,
 'upon': 26,
 'him': 27,
 'me': 28,
 'said': 29,
 'on': 30,
 'but': 31,
 'no': 32,
 'from': 33,
 'we': 34,
 'all': 35,
 'not': 36,
 'one': 37,
 'by': 38,
 'were': 39,
 'are': 40,
 'so': 41,
 'an': 42,
 'been': 43,
 'man': 44,
 'they': 45,
 'what': 46,
 'up': 47,
 'or': 48,
 'her': 49,
 'them': 50,
 'when': 51,
 'some': 52,
 'out': 53,
 'who': 54,
 'holmes': 55,
 'has': 56,
 'would': 57,
 'if': 58,
 'your': 59,
 'little': 60,
 'could': 61,
 'very': 62,
 'into': 63,
 'down': 64,
 'now': 65,
 'then': 66,
 'more': 67,
 'will': 68,
 'their': 69,
 'our': 70,
 'over': 71,
 'other': 72,
 'she': 73,
 'do': 74,
 'before': 75,
 'any': 76,
 'two': 77,
 'time': 78,
 'about': 79,
 'see': 80,
 'however': 81,
 'such': 82,

In [34]:
print(len(tokenizer.word_index))

5243


In [23]:
input_sequences = []

for sentences in content.split('\n'):
  for sentence in sentences.split('.'):
    # print(sentence)
    # print(tokenizer.texts_to_sequences([sentence])[0])

    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(tokenized_sentence)):
      input_sequences.append(tokenized_sentence[:i+1])

In [24]:
input_sequences

[[6, 223],
 [6, 223, 20],
 [6, 223, 20, 1078],
 [6, 223, 20, 1078, 2],
 [6, 223, 20, 1078, 2, 278],
 [6, 223, 20, 1078, 2, 278, 2],
 [6, 223, 20, 1078, 2, 278, 2, 1482],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2, 204],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2, 204, 3],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2, 204, 3, 677],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2, 204, 3, 677, 4],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2, 204, 3, 677, 4, 2324],
 [6, 223, 20, 1078, 2, 278, 2, 1482, 2, 1, 2323, 2, 204, 3, 677, 4, 2324, 4],
 [6,
  223,
  20,
  1078,
  2,
  278,
  2,
  1482,
  2,
  1,
  2323,
  2,
  204,
  3,
  677,
  4,
  2324,
  4,
  157],
 [6,
  223,
  20,
  1078,
  2,
  278,
  2,
  1482,
  2,
  1,
  2323,
  2,
  204,
  3,
  677,
  4,
  2324,
  4,
  157

In [26]:
max_len = max([len(x) for x in input_sequences])
max_len

87

In [28]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')
padded_input_sequences

array([[   0,    0,    0, ...,    0,    6,  223],
       [   0,    0,    0, ...,    6,  223,   20],
       [   0,    0,    0, ...,  223,   20, 1078],
       ...,
       [   0,    0,    0, ...,   50, 1225,    8],
       [   0,    0,    0, ..., 1225,    8,    4],
       [   0,    0,    0, ...,    8,    4,   28]], dtype=int32)

In [29]:
X = padded_input_sequences[:, :-1]
X

array([[   0,    0,    0, ...,    0,    0,    6],
       [   0,    0,    0, ...,    0,    6,  223],
       [   0,    0,    0, ...,    6,  223,   20],
       ...,
       [   0,    0,    0, ...,  426,   50, 1225],
       [   0,    0,    0, ...,   50, 1225,    8],
       [   0,    0,    0, ..., 1225,    8,    4]], dtype=int32)

In [31]:
y = padded_input_sequences[:, -1]
y

array([ 223,   20, 1078, ...,    8,    4,   28], dtype=int32)

In [36]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=len(tokenizer.word_index)+1)

In [37]:
y.shape

(31651, 5244)

In [38]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [40]:
model = Sequential()

model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=100, input_length=max_len-1))
model.add(LSTM(units=128))
model.add(Dense(units=len(tokenizer.word_index)+1, activation='softmax'))

In [42]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 86, 100)           524400    
                                                                 
 lstm (LSTM)                 (None, 128)               117248    
                                                                 
 dense (Dense)               (None, 5244)              676476    
                                                                 
Total params: 1318124 (5.03 MB)
Trainable params: 1318124 (5.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [43]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [44]:
model.fit(X, y, epochs=10)

Epoch 1/10
990/990 [==============================] - 37s 35ms/step - loss: 6.7363 - accuracy: 0.0616
Epoch 2/10
990/990 [==============================] - 10s 11ms/step - loss: 6.1514 - accuracy: 0.0871
Epoch 3/10
990/990 [==============================] - 10s 10ms/step - loss: 5.7413 - accuracy: 0.1109
Epoch 4/10
990/990 [==============================] - 8s 8ms/step - loss: 5.4178 - accuracy: 0.1282
Epoch 5/10
990/990 [==============================] - 8s 8ms/step - loss: 5.1226 - accuracy: 0.1409
Epoch 6/10
990/990 [==============================] - 9s 9ms/step - loss: 4.8272 - accuracy: 0.1549
Epoch 7/10
990/990 [==============================] - 9s 9ms/step - loss: 4.5348 - accuracy: 0.1716
Epoch 8/10
990/990 [==============================] - 9s 9ms/step - loss: 4.2530 - accuracy: 0.1945
Epoch 9/10
990/990 [==============================] - 9s 9ms/step - loss: 3.9813 - accuracy: 0.2197
Epoch 10/10
990/990 [==============================] - 8s 8ms/step - loss: 3.7179 - accuracy: 

In [53]:
text = "business"
# tokenize
tokenized_text = tokenizer.texts_to_sequences([text])[0]
# padding
padded_token_text =  pad_sequences([tokenized_text], maxlen=max_len-1, padding='pre')
# predict
pred = model.predict(padded_token_text)

1/1 [==============================] - 0s 357ms/step


In [56]:
pred

array([[9.5063548e-09, 2.6860962e-02, 1.0457766e-02, ..., 3.6160563e-07,
        4.3751741e-05, 5.9238970e-05]], dtype=float32)

In [57]:
pred.shape

(1, 5244)

In [58]:
import numpy as np
np.argmax(pred)

64

In [59]:
for word, index in tokenizer.word_index.items():
  if index == np.argmax(pred):
    print(word)

down


In [68]:
text = "occasion"

import time

for i in range(10):
  # tokenize
  tokenized_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text =  pad_sequences([tokenized_text], maxlen=max_len-1, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word, index in tokenizer.word_index.items():
    if index == pos:
      text += " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 21ms/step
occasion of
1/1 [==============================] - 0s 18ms/step
occasion of this
1/1 [==============================] - 0s 19ms/step
occasion of this he
1/1 [==============================] - 0s 19ms/step
occasion of this he continued
1/1 [==============================] - 0s 19ms/step
occasion of this he continued i
1/1 [==============================] - 0s 20ms/step
occasion of this he continued i have
1/1 [==============================] - 0s 19ms/step
occasion of this he continued i have already
1/1 [==============================] - 0s 19ms/step
occasion of this he continued i have already explained
1/1 [==============================] - 0s 21ms/step
occasion of this he continued i have already explained to
1/1 [==============================] - 0s 26ms/step
occasion of this he continued i have already explained to the
